build.gradle
This publishes a local JitPack artifact to mavenLocal after running the `./gradlew publishToMavenLocal` command. This enables JitPack to publish a version of the artifact we can consume remotely as well as a version we can consume locally for testing.
None.
Allows local development to publish and consume local versions of Coppuccino.
=> Publish JitPack artifact to mavenLocal

README.md
Adds instructions to the README for configuring the JitPack repository in order to pull in Coppuccino.
None.
Better documentation.
=> Add JitPack instructions to build.gradle

README.md, src/main/groovy/com/mx/coppuccino/CoppuccinoPlugin.groovy
This disables codenarc. It seems to enable itself when it detects
groovy in src/main. The rules conflict with MX's Spotless formatting
rules.
We may consider exposing a configuration that allows it to be enabled
when we can sync up the rules.
Fixes # (issue)
Please include a description of any new or modified publicly available classes and/or methods (if applicable).
This should ot impact downstream consumers.
I included an updated version in a project that that contained a lot of groovy code. The codenarc checks did not fire anymore. Also used to check an existing project. May of the rules failed the build, as expected.
=> Disable codenarc

build.gradle
This reduces the requirement of maintaining two version numbers in the build.gradle.
None.
None. Only affects maintainers.
=> Remove double version reference in build.gradle

src/main/resources/com/mx/coppuccino/config/detekt/detekt.yml
This updates the detekt configuration to the default for current
version.
A recent upgrade to detekt didn't update the configuration. The upgrade was not backward-compatible. This updates the configuration to the default (with MX style modifications) detekt configuration yaml file.
Fixes https://github.com/mxenabled/coppuccino/issues/19
None
Didn't comb through all rule changes, some projects using coppuccino may have additional style violations.
=> Fix detekt configuration

build.gradle, src/main/resources/com/mx/coppuccino/config/detekt/detekt.yml, src/main/resources/com/mx/coppuccino/config/pmd/pmd.xml
* Remove deprecated PMD rules
* Add Hush plugin
* Upgrade detekt plugin
* Upgrade spotless plugin
* Fix Detekt configuration
Need to test with major projects using plugin to ensure pipelines still work.
Publishing and testing with Path internal and external projects on Java 8 and Java 17
=> Update configurations and dependencies

src/main/resources/com/mx/coppuccino/config/checkstyle/checkstyle.xml
* Set processJavaDoc to true in checkstyle.xml
Impact unlikely
Tested with SDK libraries
=> Enable JavaDoc processing for UnusedFile check

.gitignore, build.gradle, settings.gradle, src/main/groovy/com/mx/coppuccino/CoppuccinoPlugin.groovy, src/main/resources/com/mx/coppuccino/config/detekt/detekt.yml
* Upgrade detekt plugin to 1.22.0-RC2
* Remove deprecated rules (detekt)
* Upgrade spotbugs and versions plugins
* Bump version to 3.1.3
Fixes a bug where the detekt task would fail in Kotlin projects (with `CoppuccinoKotlinExtension` enabled).
I pulled the updated version into both Java and Kotlin projects and verified it is working as expected.
=> Update detekt plugin

src/main/groovy/com/mx/coppuccino/SpotbugsConsoleReporter.groovy
=> Clean up minor spotbugs report formatting issue

src/main/groovy/com/mx/coppuccino/CoppuccinoPlugin.groovy, src/main/groovy/com/mx/coppuccino/CopyCopConfig.groovy
* Fix issue that comes from a fresh project not having the .coppuccino directory
* Refactor CopyCopConfig
Screenshot of error
Will now properly create the directory if it doesn't exist.
=> Fix pmd directory does not exist error

src/main/groovy/com/mx/coppuccino/CoppuccinoPlugin.groovy, src/main/groovy/com/mx/coppuccino/CopyCopConfig.groovy
Fix issue creating config files in multi-module projects when they don't already exist.
=> Fix problem copying config files in multi-module projects

src/main/groovy/com/mx/coppuccino/CopyCopConfig.groovy
Add check and code to explicitly create the .coppuccino directory. This fixes a build issue when the .coppuccino directory is not present.
=> fix: explicitly create .coppuccino directory

src/main/groovy/com/mx/coppuccino/CoppuccinoPlugin.groovy
Treat versions with `-rc.` as pre-releases. They will be excluded unless `excludePreReleaseVersions` is set to false.
=> fix: treat -rc. versions as pre-release

README.md, build.gradle, src/main/groovy/com/mx/coppuccino/CoppuccinoPlugin.groovy, src/main/groovy/com/mx/coppuccino/CoppuccinoPluginExtension.groovy, src/main/groovy/com/mx/coppuccino/CopyCopConfig.groovy
Introduced an `overwriteConfigs` boolean setting to allow a project to prevent Coppuccino from overwriting any configs that it is trying to manage on its own.  By default `overwriteConfigs` is set to true, which allows the original Coppuccino behavior to ensue.  When false, if Coppuccino encounters a pre-existing config file (e.g. spotbugs/exclude.xml) it will skip updating it.  
Also added a java extension with an `enabled` flag which currently controls whether Checkstyle is enabled for the project.  This is helpful for Kotlin-based projects that have no java files yet to avoid a compilation error.
Fixes #HW2-920
The optional `overwriteConfigs` and `java.enabled` settings were introduced.  For example:
```
coppuccino {
rootDir = "${projectDir}/"
overwriteConfigs = false
java {
enabled = …
```
=> feat: support config overrides and the disabling of checkstyle

jitpack.yml
Adds `jitpack.yml` and sets the JDK version to Java 17.
ref: https://github.com/jitpack/jitpack.io/blob/main/building/_index.en.md#java-version
none
none
N/A
=> fix: set jdk version in jitpack config

jitpack.yml
Follow up to https://github.com/mxenabled/coppuccino/pull/53
This removes the `before_script` config in `jitpack.yml` which is not necessary. Based on the [4.0.1 build log](https://jitpack.io/com/github/mxenabled/coppuccino/4.0.1/build.log), setting the `jdk` to `openjdk17` already adds `sdk install java 17.0.12-oracle;sdk use java 17.0.12-oracle` to the before script.
Additionally, using a custom before script to set the specific JDK version is a fragile solution, since [SDKMan](https://sdkman.io/) only has the latest minor version for each LTS version and distribution.
none
none
N/A
=> fix: remove unnecessary jitpack configs

build.gradle, gradle.properties, src/main/groovy/com/mx/coppuccino/CoppuccinoPlugin.groovy
Upgrades spotless gradle plugin to the latest version (7.0.2). This version only supports Java 11 and above, so I had to update the compatible version in build.gradle to `JavaVersion.VERSION_11`. 
This version adds the groovy formatting option `removeSemicolons` which removes unnecessary ending semicolons from groovy files. This will now be applied when using `spotlessApply`.
This version also changes how import ordering is updated by `spotlessApply`. I updated the import order for groovy and java files to behave similar to the previous functionality (though there may be some minor differences).
Additionally, this version of spotless fixes a bug that required us to include the following gradle JVM options:
```
org.gradle.jvmargs=--add-exports …
```
=> build: upgrade spotless to version 7.0.2

src/main/groovy/com/mx/coppuccino/CoppuccinoPlugin.groovy
Updates spotless import order so that unmatched imports are last. This means that an import with a prefix not specified in the `importOrder` configuration will appear below all of the other imports.
For example:
```java
import java.util.Objects;
import java.util.Random;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import org.apache.commons.lang3.StringUtils;
import my.package;
import some.other.package;
```
In the above example, `my.package` and `some.other.package` are grouped after all of the more common package prefixes (`java`, `com`, `org`, etc.).
I pulled a snapshot version into path-connector-globalcu and ran `./gradlew spotlessApply` and verified that imports were updated to the expected order. 
Java example:
```java
package globalcu.connection.utils;
import …
```
=> feat(spotless): move other imports to last

src/main/groovy/com/mx/coppuccino/CoppuccinoPlugin.groovy, src/main/groovy/com/mx/coppuccino/SpotbugsConsoleReporter.groovy
`SpotbugsConsoleReporter` displays the result of failed spotbugs tasks in the console. However, this functionality was not working for Gradle multi-project builds. The root cause was that the implementation included a hard coded file path for the spotbugs report.
This change resolves the issue by using a relative file path for the report:
```groovy
"${project.extensions.spotbugs.reportsDir.get()}/main.xml"
```
If the report file is not found in the expected location, a `FileNotFoundException` will be thrown.
Additionally, this adds the `lombok` import prefix to the groovy `importOrder` spotless configuration. While Lombok is used less frequently in Groovy files, it is still used in some projects and should be handled appropriately.
`./gradlew spotbugsMain` will now display errors in the …
=> fix(spotbugs): remove hardcoded report path in console reporter

src/main/groovy/com/mx/coppuccino/CoppuccinoPlugin.groovy, src/main/groovy/com/mx/coppuccino/CopyCopConfig.groovy, src/main/resources/com/mx/coppuccino/config/detekt/detekt.yml, src/main/resources/com/mx/coppuccino/config/spotless/.editorconfig
Spotless uses [Ktlint](https://pinterest.github.io/ktlint/latest/) to perform code style checks in Kotlin projects. We previously had Ktlint locked to version `0.39.0` and provided rules via the `userData` method. However, this method was removed in a previous version of Spotless and needs to be replaced with a different configuration method.
This MR updates Ktlint to use the latest version (currently `1.5.0`) with a custom configuration. This configuration is provided in an `.editorconfig` file that contains the following rules:
```
[*]
indent_style = space
indent_size = 2
max_line_length = 150
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
[*.{kt,kts}]
ktlint_code_style = intellij_idea
ktlint_standard = enabled …
```
=> feat(spotless): use latest ktlint version with custom config
